
#ifndef _PPT_WM_USER_DEF_H__
#define _PPT_WM_USER_DEF_H__

#pragma once

#define WM_USER_NOUPDATE						WM_USER + 1
#define WM_USER_GET_EDITION						WM_USER + 2
#define WM_USER_SWITCH_CHAPTER					WM_USER + 3
#define WM_USER_GET_COURSE						WM_USER + 4

#define WM_LOCAL_SEARCH_REFRESH_WINDOW			WM_USER + 60
#define WM_LOCAL_SEARCH_REFRESH_WINDOW_FINISH	WM_USER + 61
#define WM_LOGIN_COMPLETE						WM_USER + 62
#define WM_SENDBTN_DELAY						WM_USER + 63
#define WM_REGISTER_COMPLETE					WM_USER + 64
#define WM_CHANGEPASS_COMPLETE					WM_USER + 65
#define WM_RESETPWD_SUCCESS						WM_USER + 66

#define WM_INITPPT								WM_USER + 200
#define WM_INITSHOWGUIDE						WM_USER + 201

#define WM_USER_HIDE							WM_USER + 500
#define WM_USER_FOCUS							WM_USER + 501

#define WM_USER_PPT_EXPOERT_IMAGES				WM_USER + 600

#define WM_USER_PACK_PPT						WM_USER + 701

#define WM_SHOW_UPDATETIP						WM_USER + 801
#define WM_SHOW_UPDATEINFO						WM_USER + 802

#define WM_SHOW_ADD_SLIDE_WINDOW				WM_USER + 901
#define WM_SHOW_EXER_EDIT_WINDOW				WM_USER + 902
#define WM_SHOW_VR_DISTRIBUTE_WINDOW			WM_USER + 903

#define WM_CHECK_UPDATE							WM_USER + 999

#define WM_CREATE_GUIDE							WM_USER + 1000
#define WM_EXIT_PROCESS							WM_USER + 1001
#define WM_NOTIFY_UPDATE						WM_USER + 1002
#define WM_TITLEBUTTON_OPERATION				WM_USER + 1003
#define WM_PPT_FILE_OPERATION					WM_USER + 1004
#define WM_SHOW_SHADE							WM_USER + 1005
#define WM_HIDE_SHADE							WM_USER + 1006
#define WM_SHOW_UCLOGIN							WM_USER + 1007

#define WM_USER_PPT_CONTROL						WM_USER + 7001
#define WM_CRATE_QUESTION_THUMBNAIL				WM_USER + 7002

#define WM_TITLE_MOUSE							WM_USER + 8000
#define WM_USER_SEND_EVENT						WM_USER + 8001
#define WM_USER_POST_EVENT						WM_USER + 8002

#define WM_USER_CPLAYER_SET_MESSAGE_WND			WM_USER + 8897
#define WM_USER_CPLAYER_PPT_PAGE				WM_USER + 8898
#define WM_USER_CPLAYER_NAVI_URL				WM_USER + 8899

#define WM_USER_HTTP_DOWNLOAD					WM_USER + 9001
#define WM_USER_HTTP_UPLOAD						WM_USER + 9002

#define WM_DOWNLOAD_MANAGER_CLOSE				WM_USER + 2000


#endif	// _PPT_WM_USER_DEF_H__
